In [311]:
learning_rate = [0.7, 0.5]
hidden_sizes = [35]
step_size = 3

features = ['Close', 'SPX', 'DXY', 'CPI', 'Fed Rate']
nav = []
price = []
dates = []
funds = 100000000
for i in range(1,3):
    df = pd.read_csv(f'data/train{i}.csv')
    data = torch.from_numpy(df[features].to_numpy())
    prices = torch.from_numpy(df['Open'].to_numpy())
    
    df2 = pd.read_csv(f'data/predict{i}.csv')
    data2 = torch.from_numpy(df2[features].to_numpy())
    prices2 = torch.from_numpy(df2['Open'].to_numpy())

    lowest_loss = 10000
    lowest_seq = Sequence()
    lowest_rate = 0
    lowest_size = 0
    for r in learning_rate:
        for h in hidden_sizes:
            train_loss, test_loss, seq = train(
                r, 
                data, 
                prices,
                step_size
            )
            if test_loss < lowest_loss:
                lowest_loss = test_loss
                lowest_seq = seq
                lowest_rate = r
                lowest_size = h
    
    print("Training completed with loss: ", lowest_loss)
    n, p = test2(
        funds,
        data2, 
        prices2,
        lowest_seq,
    )
    
    nav = nav + n
    price = price + p
    dates = dates + df2['Date'][29:].tolist()
    funds = n[-1]
    print(lowest_rate, lowest_size)
    
# draw the result
print("finished")
plt.figure(figsize=(10, 5))
plt.plot(dates, nav, label='NAV', color='green')
plt.savefig('nav.pdf')
plt.close()

plt.figure(figsize=(10, 5))
plt.plot(dates, price, label='P', color='black')
plt.savefig('p.pdf')
plt.close()

nav = [float(tensor.item()) for tensor in nav]
df = pd.DataFrame({
    'Date': dates,
    'NAV': nav
})

# Save the DataFrame to an Excel file
df.to_excel('nav.xlsx', index=False)

Begin Training
STEP:  0
tensor([0.6785, 0.3162], dtype=torch.float64)
tensor([0.6521, 0.3388], dtype=torch.float64)
tensor([0.6047, 0.3789], dtype=torch.float64)
tensor([0.5642, 0.4123], dtype=torch.float64)
tensor([0.5402, 0.4313], dtype=torch.float64)
tensor([0.5357, 0.4341], dtype=torch.float64)
tensor([0.5627, 0.4108], dtype=torch.float64)
tensor([0.6201, 0.3626], dtype=torch.float64)
tensor([0.6852, 0.3089], dtype=torch.float64)
tensor([0.7259, 0.2758], dtype=torch.float64)
tensor([0.7482, 0.2580], dtype=torch.float64)
tensor([0.7627, 0.2464], dtype=torch.float64)
tensor([0.7654, 0.2445], dtype=torch.float64)
tensor([0.7638, 0.2462], dtype=torch.float64)
tensor([0.7895, 0.2251], dtype=torch.float64)
tensor([0.8223, 0.1981], dtype=torch.float64)
tensor([0.8533, 0.1729], dtype=torch.float64)
tensor([0.8654, 0.1634], dtype=torch.float64)
tensor([0.8705, 0.1597], dtype=torch.float64)
tensor([0.8937, 0.1411], dtype=torch.float64)
tensor([0.9059, 0.1315], dtype=torch.float64)
tensor([0.

tensor([0.2238, 0.6894], dtype=torch.float64)
tensor([0.1837, 0.7221], dtype=torch.float64)
tensor([0.1624, 0.7391], dtype=torch.float64)
tensor([0.1552, 0.7449], dtype=torch.float64)
tensor([0.1613, 0.7400], dtype=torch.float64)
tensor([0.1603, 0.7412], dtype=torch.float64)
tensor([0.1648, 0.7380], dtype=torch.float64)
tensor([0.1736, 0.7311], dtype=torch.float64)
tensor([0.1913, 0.7169], dtype=torch.float64)
tensor([0.1935, 0.7156], dtype=torch.float64)
tensor([0.1989, 0.7116], dtype=torch.float64)
tensor([0.2278, 0.6877], dtype=torch.float64)
tensor([0.2723, 0.6508], dtype=torch.float64)
tensor([0.2912, 0.6355], dtype=torch.float64)
tensor([0.2865, 0.6400], dtype=torch.float64)
tensor([0.2900, 0.6370], dtype=torch.float64)
tensor([0.2812, 0.6443], dtype=torch.float64)
tensor([0.2882, 0.6383], dtype=torch.float64)
tensor([0.3097, 0.6201], dtype=torch.float64)
tensor([0.3810, 0.5601], dtype=torch.float64)
tensor([0.4528, 0.5002], dtype=torch.float64)
tensor([0.4835, 0.4753], dtype=tor

tensor([0.3088, 0.6197], dtype=torch.float64)
tensor([0.3380, 0.5951], dtype=torch.float64)
tensor([0.3556, 0.5801], dtype=torch.float64)
tensor([0.3469, 0.5872], dtype=torch.float64)
tensor([0.3021, 0.6241], dtype=torch.float64)
tensor([0.2645, 0.6545], dtype=torch.float64)
tensor([0.2256, 0.6854], dtype=torch.float64)
tensor([0.1855, 0.7172], dtype=torch.float64)
tensor([0.1505, 0.7445], dtype=torch.float64)
tensor([0.1310, 0.7593], dtype=torch.float64)
tensor([0.1110, 0.7746], dtype=torch.float64)
tensor([0.0924, 0.7893], dtype=torch.float64)
tensor([0.0883, 0.7922], dtype=torch.float64)
tensor([0.1117, 0.7732], dtype=torch.float64)
tensor([0.1449, 0.7462], dtype=torch.float64)
tensor([0.2004, 0.7005], dtype=torch.float64)
tensor([0.2711, 0.6424], dtype=torch.float64)
tensor([0.3456, 0.5814], dtype=torch.float64)
tensor([0.4573, 0.4895], dtype=torch.float64)
tensor([0.5621, 0.4040], dtype=torch.float64)
tensor([0.6356, 0.3450], dtype=torch.float64)
tensor([0.6893, 0.3026], dtype=tor

tensor([0.2044, 0.7037], dtype=torch.float64)
tensor([0.1957, 0.7110], dtype=torch.float64)
tensor([0.1881, 0.7176], dtype=torch.float64)
tensor([0.1776, 0.7266], dtype=torch.float64)
tensor([0.1740, 0.7298], dtype=torch.float64)
tensor([0.1698, 0.7333], dtype=torch.float64)
tensor([0.1976, 0.7102], dtype=torch.float64)
tensor([0.2434, 0.6723], dtype=torch.float64)
tensor([0.3075, 0.6195], dtype=torch.float64)
tensor([0.3950, 0.5472], dtype=torch.float64)
tensor([0.4908, 0.4683], dtype=torch.float64)
tensor([0.5767, 0.3979], dtype=torch.float64)
tensor([0.6690, 0.3221], dtype=torch.float64)
tensor([0.7534, 0.2528], dtype=torch.float64)
tensor([0.8190, 0.1994], dtype=torch.float64)
tensor([0.8593, 0.1667], dtype=torch.float64)
tensor([0.9037, 0.1309], dtype=torch.float64)
tensor([0.9310, 0.1091], dtype=torch.float64)
tensor([0.9290, 0.1117], dtype=torch.float64)
tensor([0.9048, 0.1324], dtype=torch.float64)
tensor([0.8404, 0.1859], dtype=torch.float64)
tensor([0.8139, 0.2077], dtype=tor

tensor([0.8199, 0.2011], dtype=torch.float64)
tensor([0.8103, 0.2094], dtype=torch.float64)
tensor([0.7899, 0.2265], dtype=torch.float64)
tensor([0.7646, 0.2475], dtype=torch.float64)
tensor([0.7091, 0.2933], dtype=torch.float64)
tensor([0.6446, 0.3465], dtype=torch.float64)
tensor([0.5918, 0.3896], dtype=torch.float64)
tensor([0.5373, 0.4341], dtype=torch.float64)
tensor([0.4723, 0.4879], dtype=torch.float64)
tensor([0.4165, 0.5339], dtype=torch.float64)
tensor([0.3806, 0.5631], dtype=torch.float64)
tensor([0.3434, 0.5936], dtype=torch.float64)
tensor([0.2897, 0.6380], dtype=torch.float64)
tensor([0.2433, 0.6758], dtype=torch.float64)
tensor([0.2245, 0.6903], dtype=torch.float64)
tensor([0.2071, 0.7039], dtype=torch.float64)
tensor([0.1993, 0.7097], dtype=torch.float64)
tensor([0.1975, 0.7107], dtype=torch.float64)
tensor([0.1990, 0.7092], dtype=torch.float64)
tensor([0.2125, 0.6975], dtype=torch.float64)
tensor([0.2330, 0.6799], dtype=torch.float64)
tensor([0.2636, 0.6539], dtype=tor

tensor([0.5934, 0.3820], dtype=torch.float64)
tensor([0.5996, 0.3765], dtype=torch.float64)
tensor([0.6031, 0.3735], dtype=torch.float64)
tensor([0.6084, 0.3690], dtype=torch.float64)
tensor([0.6188, 0.3607], dtype=torch.float64)
tensor([0.6272, 0.3541], dtype=torch.float64)
tensor([0.6418, 0.3426], dtype=torch.float64)
tensor([0.6587, 0.3291], dtype=torch.float64)
tensor([0.6716, 0.3188], dtype=torch.float64)
tensor([0.6764, 0.3155], dtype=torch.float64)
tensor([0.6694, 0.3216], dtype=torch.float64)
tensor([0.6539, 0.3350], dtype=torch.float64)
tensor([0.6317, 0.3543], dtype=torch.float64)
up correct: 287/816
down correct: 563/847
total correct: 850/1663
omitted: 0/1663
STEP:  1
tensor([0.7157, 0.2779], dtype=torch.float64)
tensor([0.4292, 0.5777], dtype=torch.float64)
tensor([0.2300, 0.7902], dtype=torch.float64)
tensor([0.2461, 0.7759], dtype=torch.float64)
tensor([0.3469, 0.6701], dtype=torch.float64)
tensor([0.4958, 0.5130], dtype=torch.float64)
tensor([0.7812, 0.2146], dtype=torc

tensor([-0.1529,  1.1768], dtype=torch.float64)
tensor([-0.1089,  1.1293], dtype=torch.float64)
tensor([-0.0616,  1.0782], dtype=torch.float64)
tensor([-0.0885,  1.1052], dtype=torch.float64)
tensor([-0.1084,  1.1272], dtype=torch.float64)
tensor([-0.1733,  1.1961], dtype=torch.float64)
tensor([-0.1830,  1.2087], dtype=torch.float64)
tensor([-0.2032,  1.2320], dtype=torch.float64)
tensor([-0.1750,  1.2051], dtype=torch.float64)
tensor([-0.2222,  1.2555], dtype=torch.float64)
tensor([-0.2215,  1.2568], dtype=torch.float64)
tensor([-0.1117,  1.1444], dtype=torch.float64)
tensor([0.0117, 1.0167], dtype=torch.float64)
tensor([-0.0831,  1.1151], dtype=torch.float64)
tensor([-0.1637,  1.2000], dtype=torch.float64)
tensor([-0.1043,  1.1392], dtype=torch.float64)
tensor([-0.1720,  1.2092], dtype=torch.float64)
tensor([-0.0796,  1.1137], dtype=torch.float64)
tensor([0.0403, 0.9877], dtype=torch.float64)
tensor([0.5211, 0.4871], dtype=torch.float64)
tensor([0.6595, 0.3374], dtype=torch.float64)


tensor([0.4731, 0.5105], dtype=torch.float64)
tensor([0.2518, 0.7395], dtype=torch.float64)
tensor([-0.0029,  1.0070], dtype=torch.float64)
tensor([-0.2448,  1.2640], dtype=torch.float64)
tensor([-0.3037,  1.3307], dtype=torch.float64)
tensor([-0.2824,  1.3118], dtype=torch.float64)
tensor([-0.3098,  1.3414], dtype=torch.float64)
tensor([-0.2762,  1.3089], dtype=torch.float64)
tensor([-0.2124,  1.2460], dtype=torch.float64)
tensor([-0.2520,  1.2902], dtype=torch.float64)
tensor([-0.3083,  1.3508], dtype=torch.float64)
tensor([-0.1946,  1.2346], dtype=torch.float64)
tensor([-0.2920,  1.3362], dtype=torch.float64)
tensor([-0.3070,  1.3537], dtype=torch.float64)
tensor([-0.2276,  1.2714], dtype=torch.float64)
tensor([-0.1978,  1.2378], dtype=torch.float64)
tensor([-0.1259,  1.1606], dtype=torch.float64)
tensor([0.0867, 0.9375], dtype=torch.float64)
tensor([0.1490, 0.8692], dtype=torch.float64)
tensor([0.1505, 0.8658], dtype=torch.float64)
tensor([0.2245, 0.7880], dtype=torch.float64)
tens

tensor([0.3580, 0.6422], dtype=torch.float64)
tensor([-0.0259,  1.0442], dtype=torch.float64)
tensor([-0.0546,  1.0762], dtype=torch.float64)
tensor([0.0425, 0.9728], dtype=torch.float64)
tensor([0.0164, 0.9957], dtype=torch.float64)
tensor([-0.0114,  1.0227], dtype=torch.float64)
tensor([-0.1006,  1.1151], dtype=torch.float64)
tensor([-0.0813,  1.0970], dtype=torch.float64)
tensor([-0.1348,  1.1538], dtype=torch.float64)
tensor([-0.1541,  1.1753], dtype=torch.float64)
tensor([-0.0895,  1.1085], dtype=torch.float64)
tensor([-0.1227,  1.1427], dtype=torch.float64)
tensor([0.0033, 1.0135], dtype=torch.float64)
tensor([0.0410, 0.9755], dtype=torch.float64)
tensor([0.2009, 0.8123], dtype=torch.float64)
tensor([0.5000, 0.5033], dtype=torch.float64)
tensor([0.7271, 0.2675], dtype=torch.float64)
tensor([0.8806, 0.1079], dtype=torch.float64)
tensor([ 1.1527, -0.1730], dtype=torch.float64)
tensor([ 1.2319, -0.2579], dtype=torch.float64)
tensor([ 1.2656, -0.2941], dtype=torch.float64)
tensor([ 1

tensor([ 1.0877, -0.1131], dtype=torch.float64)
tensor([ 1.0189, -0.0426], dtype=torch.float64)
tensor([ 1.0748, -0.0980], dtype=torch.float64)
tensor([ 1.0377, -0.0596], dtype=torch.float64)
tensor([0.9640, 0.0173], dtype=torch.float64)
tensor([0.9285, 0.0553], dtype=torch.float64)
tensor([0.8887, 0.0974], dtype=torch.float64)
tensor([0.8744, 0.1128], dtype=torch.float64)
tensor([0.6431, 0.3516], dtype=torch.float64)
tensor([0.4300, 0.5750], dtype=torch.float64)
tensor([0.3738, 0.6360], dtype=torch.float64)
tensor([0.1690, 0.8499], dtype=torch.float64)
tensor([-0.0422,  1.0725], dtype=torch.float64)
tensor([-0.1110,  1.1465], dtype=torch.float64)
tensor([-0.0436,  1.0768], dtype=torch.float64)
tensor([-0.0564,  1.0877], dtype=torch.float64)
tensor([-0.1543,  1.1871], dtype=torch.float64)
tensor([-0.0818,  1.1093], dtype=torch.float64)
tensor([0.0126, 1.0077], dtype=torch.float64)
tensor([-0.0101,  1.0278], dtype=torch.float64)
tensor([0.0170, 0.9979], dtype=torch.float64)
tensor([0.00

tensor([0.7332, 0.2495], dtype=torch.float64)
tensor([0.6701, 0.3158], dtype=torch.float64)
tensor([0.7282, 0.2572], dtype=torch.float64)
tensor([0.7636, 0.2198], dtype=torch.float64)
tensor([0.7350, 0.2481], dtype=torch.float64)
tensor([0.7354, 0.2476], dtype=torch.float64)
tensor([0.7479, 0.2345], dtype=torch.float64)
tensor([0.7335, 0.2485], dtype=torch.float64)
tensor([0.8403, 0.1386], dtype=torch.float64)
tensor([0.8644, 0.1113], dtype=torch.float64)
tensor([0.7809, 0.1955], dtype=torch.float64)
tensor([0.8934, 0.0803], dtype=torch.float64)
tensor([0.8657, 0.1054], dtype=torch.float64)
tensor([0.8891, 0.0809], dtype=torch.float64)
tensor([0.9137, 0.0541], dtype=torch.float64)
tensor([0.9512, 0.0157], dtype=torch.float64)
tensor([0.9352, 0.0319], dtype=torch.float64)
tensor([0.9664, 0.0011], dtype=torch.float64)
tensor([ 0.9784, -0.0108], dtype=torch.float64)
tensor([0.9443, 0.0248], dtype=torch.float64)
tensor([0.9611, 0.0094], dtype=torch.float64)
tensor([0.8893, 0.0832], dtype=t

tensor([0.0560, 0.9355], dtype=torch.float64)
tensor([0.0021, 0.9973], dtype=torch.float64)
tensor([0.0018, 1.0006], dtype=torch.float64)
tensor([-0.0073,  1.0125], dtype=torch.float64)
tensor([-0.0555,  1.0602], dtype=torch.float64)
tensor([-0.0362,  1.0367], dtype=torch.float64)
tensor([-0.0749,  1.0729], dtype=torch.float64)
tensor([-0.0365,  1.0305], dtype=torch.float64)
tensor([-0.0710,  1.0625], dtype=torch.float64)
tensor([-0.0319,  1.0194], dtype=torch.float64)
tensor([-0.0733,  1.0598], dtype=torch.float64)
tensor([-0.0344,  1.0176], dtype=torch.float64)
tensor([0.0190, 0.9616], dtype=torch.float64)
tensor([0.0797, 0.8962], dtype=torch.float64)
tensor([-0.0940,  1.0715], dtype=torch.float64)
tensor([-0.0022,  0.9758], dtype=torch.float64)
tensor([0.0388, 0.9368], dtype=torch.float64)
tensor([-0.0785,  1.0567], dtype=torch.float64)
tensor([0.0753, 0.8990], dtype=torch.float64)
tensor([0.0852, 0.8908], dtype=torch.float64)
tensor([0.7573, 0.2023], dtype=torch.float64)
tensor([0.

tensor([0.1082, 0.8782], dtype=torch.float64)
tensor([0.0595, 0.9318], dtype=torch.float64)
tensor([-0.0558,  1.0522], dtype=torch.float64)
tensor([0.1291, 0.8718], dtype=torch.float64)
tensor([-0.0117,  1.0255], dtype=torch.float64)
tensor([0.0404, 0.9781], dtype=torch.float64)
tensor([0.0258, 1.0000], dtype=torch.float64)
tensor([0.0119, 1.0183], dtype=torch.float64)
tensor([5.3387e-04, 1.0335e+00], dtype=torch.float64)
tensor([-0.0260,  1.0613], dtype=torch.float64)
tensor([0.0166, 1.0191], dtype=torch.float64)
tensor([-0.0271,  1.0589], dtype=torch.float64)
tensor([0.0898, 0.9372], dtype=torch.float64)
tensor([0.2959, 0.7201], dtype=torch.float64)
tensor([0.5399, 0.4628], dtype=torch.float64)
tensor([0.7177, 0.2789], dtype=torch.float64)
tensor([ 1.0969, -0.0789], dtype=torch.float64)
tensor([0.9860, 0.0363], dtype=torch.float64)
tensor([0.9569, 0.0514], dtype=torch.float64)
tensor([0.9862, 0.0132], dtype=torch.float64)
tensor([ 1.0411, -0.0401], dtype=torch.float64)
tensor([ 1.016

tensor([ 1.0731, -0.0522], dtype=torch.float64)
tensor([0.9887, 0.0377], dtype=torch.float64)
tensor([0.9993, 0.0311], dtype=torch.float64)
tensor([1.0007, 0.0292], dtype=torch.float64)
tensor([1.0299e+00, 8.0211e-04], dtype=torch.float64)
tensor([ 1.0401, -0.0067], dtype=torch.float64)
tensor([ 1.0322e+00, -3.9659e-04], dtype=torch.float64)
tensor([ 1.0539, -0.0157], dtype=torch.float64)
tensor([1.0294, 0.0062], dtype=torch.float64)
tensor([ 1.0552, -0.0138], dtype=torch.float64)
tensor([1.0462e+00, 4.7706e-04], dtype=torch.float64)
tensor([1.0234, 0.0173], dtype=torch.float64)
tensor([ 1.0490, -0.0063], dtype=torch.float64)
tensor([0.8693, 0.1622], dtype=torch.float64)
tensor([0.8303, 0.1842], dtype=torch.float64)
tensor([0.7786, 0.2255], dtype=torch.float64)
tensor([0.6009, 0.3987], dtype=torch.float64)
tensor([0.0239, 0.9751], dtype=torch.float64)
tensor([0.0502, 0.9301], dtype=torch.float64)
tensor([0.0098, 0.9694], dtype=torch.float64)
tensor([0.0396, 0.9453], dtype=torch.float64

tensor([0.0786, 0.8925], dtype=torch.float64)
tensor([0.0065, 0.9732], dtype=torch.float64)
tensor([-0.0257,  1.0095], dtype=torch.float64)
tensor([0.0587, 0.9312], dtype=torch.float64)
tensor([0.0166, 0.9809], dtype=torch.float64)
tensor([-0.0438,  1.0442], dtype=torch.float64)
tensor([0.0145, 0.9859], dtype=torch.float64)
tensor([-0.0380,  1.0402], dtype=torch.float64)
tensor([-0.0066,  1.0082], dtype=torch.float64)
tensor([0.0773, 0.9257], dtype=torch.float64)
tensor([0.0765, 0.9286], dtype=torch.float64)
tensor([0.2392, 0.7624], dtype=torch.float64)
tensor([0.5011, 0.4906], dtype=torch.float64)
tensor([0.4344, 0.5580], dtype=torch.float64)
tensor([0.4929, 0.4950], dtype=torch.float64)
tensor([0.6796, 0.3039], dtype=torch.float64)
tensor([0.7437, 0.2420], dtype=torch.float64)
tensor([0.5627, 0.4222], dtype=torch.float64)
tensor([0.8095, 0.1721], dtype=torch.float64)
tensor([0.7681, 0.2178], dtype=torch.float64)
tensor([0.7284, 0.2595], dtype=torch.float64)
tensor([0.5116, 0.4759], d

tensor([0.9047, 0.1027], dtype=torch.float64)
tensor([0.9026, 0.1051], dtype=torch.float64)
tensor([0.9671, 0.0433], dtype=torch.float64)
tensor([0.9498, 0.0607], dtype=torch.float64)
tensor([0.9902, 0.0204], dtype=torch.float64)
tensor([0.9838, 0.0259], dtype=torch.float64)
tensor([0.9624, 0.0432], dtype=torch.float64)
tensor([0.9855, 0.0213], dtype=torch.float64)
tensor([0.9239, 0.0800], dtype=torch.float64)
tensor([0.8468, 0.1501], dtype=torch.float64)
tensor([0.7168, 0.2721], dtype=torch.float64)
up correct: 341/816
down correct: 476/847
total correct: 817/1663
omitted: 0/1663
Begin Training
STEP:  0
tensor([0.9241, 0.0388], dtype=torch.float64)
tensor([0.8986, 0.0630], dtype=torch.float64)
tensor([0.8305, 0.1279], dtype=torch.float64)
tensor([0.7778, 0.1781], dtype=torch.float64)
tensor([0.7574, 0.1972], dtype=torch.float64)
tensor([0.7617, 0.1930], dtype=torch.float64)
tensor([0.7995, 0.1573], dtype=torch.float64)
tensor([0.8784, 0.0823], dtype=torch.float64)
tensor([9.6448e-01, 

tensor([0.3773, 0.5675], dtype=torch.float64)
tensor([0.2874, 0.6586], dtype=torch.float64)
tensor([0.2260, 0.7227], dtype=torch.float64)
tensor([0.1856, 0.7663], dtype=torch.float64)
tensor([0.1701, 0.7858], dtype=torch.float64)
tensor([0.1848, 0.7748], dtype=torch.float64)
tensor([0.1963, 0.7649], dtype=torch.float64)
tensor([0.2157, 0.7470], dtype=torch.float64)
tensor([0.2492, 0.7147], dtype=torch.float64)
tensor([0.3013, 0.6637], dtype=torch.float64)
tensor([0.3272, 0.6364], dtype=torch.float64)
tensor([0.3544, 0.6085], dtype=torch.float64)
tensor([0.4228, 0.5413], dtype=torch.float64)
tensor([0.5243, 0.4413], dtype=torch.float64)
tensor([0.5774, 0.3860], dtype=torch.float64)
tensor([0.5735, 0.3860], dtype=torch.float64)
tensor([0.5801, 0.3775], dtype=torch.float64)
tensor([0.5747, 0.3806], dtype=torch.float64)
tensor([0.5889, 0.3656], dtype=torch.float64)
tensor([0.6219, 0.3329], dtype=torch.float64)
tensor([0.7173, 0.2415], dtype=torch.float64)
tensor([0.8165, 0.1456], dtype=tor

tensor([0.4306, 0.5224], dtype=torch.float64)
tensor([0.4085, 0.5443], dtype=torch.float64)
tensor([0.4526, 0.5030], dtype=torch.float64)
tensor([0.5142, 0.4434], dtype=torch.float64)
tensor([0.5599, 0.3985], dtype=torch.float64)
tensor([0.6008, 0.3582], dtype=torch.float64)
tensor([0.6275, 0.3315], dtype=torch.float64)
tensor([0.5988, 0.3576], dtype=torch.float64)
tensor([0.5084, 0.4444], dtype=torch.float64)
tensor([0.4107, 0.5400], dtype=torch.float64)
tensor([0.3092, 0.6412], dtype=torch.float64)
tensor([0.2046, 0.7468], dtype=torch.float64)
tensor([0.1109, 0.8429], dtype=torch.float64)
tensor([0.0418, 0.9157], dtype=torch.float64)
tensor([-0.0110,  0.9713], dtype=torch.float64)
tensor([-0.0543,  1.0173], dtype=torch.float64)
tensor([-0.0813,  1.0472], dtype=torch.float64)
tensor([-0.0821,  1.0529], dtype=torch.float64)
tensor([-0.0511,  1.0247], dtype=torch.float64)
tensor([0.0286, 0.9492], dtype=torch.float64)
tensor([0.1784, 0.8036], dtype=torch.float64)
tensor([0.3744, 0.6105],

tensor([0.3728, 0.5949], dtype=torch.float64)
tensor([0.5171, 0.4541], dtype=torch.float64)
tensor([0.6863, 0.2886], dtype=torch.float64)
tensor([0.8398, 0.1371], dtype=torch.float64)
tensor([0.9375, 0.0390], dtype=torch.float64)
tensor([ 1.0070, -0.0311], dtype=torch.float64)
tensor([ 1.0713, -0.0956], dtype=torch.float64)
tensor([ 1.1007, -0.1257], dtype=torch.float64)
tensor([ 1.1067, -0.1326], dtype=torch.float64)
tensor([ 1.1212, -0.1472], dtype=torch.float64)
tensor([ 1.1482, -0.1742], dtype=torch.float64)
tensor([ 1.1487, -0.1753], dtype=torch.float64)
tensor([ 1.1077, -0.1362], dtype=torch.float64)
tensor([ 1.0390, -0.0708], dtype=torch.float64)
tensor([ 0.9861, -0.0205], dtype=torch.float64)
tensor([0.9260, 0.0366], dtype=torch.float64)
tensor([0.8353, 0.1227], dtype=torch.float64)
tensor([0.7699, 0.1850], dtype=torch.float64)
tensor([0.7589, 0.1959], dtype=torch.float64)
tensor([0.7856, 0.1712], dtype=torch.float64)
tensor([0.8162, 0.1430], dtype=torch.float64)
tensor([0.8655

tensor([0.7803, 0.1742], dtype=torch.float64)
tensor([0.7352, 0.2170], dtype=torch.float64)
tensor([0.7065, 0.2440], dtype=torch.float64)
tensor([0.6509, 0.2966], dtype=torch.float64)
tensor([0.6064, 0.3392], dtype=torch.float64)
tensor([0.5818, 0.3630], dtype=torch.float64)
tensor([0.5419, 0.4016], dtype=torch.float64)
tensor([0.4660, 0.4756], dtype=torch.float64)
tensor([0.3771, 0.5637], dtype=torch.float64)
tensor([0.3321, 0.6110], dtype=torch.float64)
tensor([0.2956, 0.6497], dtype=torch.float64)
tensor([0.2695, 0.6784], dtype=torch.float64)
tensor([0.2578, 0.6930], dtype=torch.float64)
tensor([0.2521, 0.7011], dtype=torch.float64)
tensor([0.2599, 0.6956], dtype=torch.float64)
tensor([0.2842, 0.6737], dtype=torch.float64)
tensor([0.3309, 0.6294], dtype=torch.float64)
tensor([0.4263, 0.5381], dtype=torch.float64)
tensor([0.5215, 0.4449], dtype=torch.float64)
tensor([0.5989, 0.3683], dtype=torch.float64)
tensor([0.6727, 0.2952], dtype=torch.float64)
tensor([0.7352, 0.2326], dtype=tor

tensor([0.8738, 0.0794], dtype=torch.float64)
tensor([0.8437, 0.1082], dtype=torch.float64)
up correct: 619/816
down correct: 207/847
total correct: 826/1663
omitted: 0/1663
STEP:  1
tensor([0.7461, 0.2815], dtype=torch.float64)
tensor([0.6327, 0.3930], dtype=torch.float64)
tensor([0.4628, 0.5591], dtype=torch.float64)
tensor([0.3713, 0.6480], dtype=torch.float64)
tensor([0.3674, 0.6513], dtype=torch.float64)
tensor([0.4278, 0.5923], dtype=torch.float64)
tensor([0.5772, 0.4472], dtype=torch.float64)
tensor([0.7792, 0.2505], dtype=torch.float64)
tensor([0.9291, 0.1039], dtype=torch.float64)
tensor([0.9661, 0.0676], dtype=torch.float64)
tensor([0.9499, 0.0836], dtype=torch.float64)
tensor([0.9334, 0.0992], dtype=torch.float64)
tensor([0.9023, 0.1289], dtype=torch.float64)
tensor([0.8727, 0.1570], dtype=torch.float64)
tensor([0.9322, 0.0972], dtype=torch.float64)
tensor([1.0016, 0.0275], dtype=torch.float64)
tensor([ 1.0523, -0.0231], dtype=torch.float64)
tensor([ 1.0489, -0.0197], dtype=

tensor([-0.1305,  1.1287], dtype=torch.float64)
tensor([-0.1741,  1.1686], dtype=torch.float64)
tensor([-0.1709,  1.1639], dtype=torch.float64)
tensor([-0.1417,  1.1350], dtype=torch.float64)
tensor([-0.1110,  1.1064], dtype=torch.float64)
tensor([-0.0724,  1.0714], dtype=torch.float64)
tensor([-0.0754,  1.0758], dtype=torch.float64)
tensor([-0.0750,  1.0772], dtype=torch.float64)
tensor([-0.0697,  1.0740], dtype=torch.float64)
tensor([-0.0405,  1.0476], dtype=torch.float64)
tensor([-0.0605,  1.0674], dtype=torch.float64)
tensor([-0.0701,  1.0778], dtype=torch.float64)
tensor([-5.4529e-04,  1.0128e+00], dtype=torch.float64)
tensor([0.1222, 0.8968], dtype=torch.float64)
tensor([0.1365, 0.8836], dtype=torch.float64)
tensor([0.0684, 0.9490], dtype=torch.float64)
tensor([0.0526, 0.9646], dtype=torch.float64)
tensor([0.0091, 1.0059], dtype=torch.float64)
tensor([0.0300, 0.9854], dtype=torch.float64)
tensor([0.1031, 0.9147], dtype=torch.float64)
tensor([0.3565, 0.6709], dtype=torch.float64)


tensor([-0.1262,  1.1324], dtype=torch.float64)
tensor([-0.1115,  1.1174], dtype=torch.float64)
tensor([0.0166, 0.9951], dtype=torch.float64)
tensor([0.1438, 0.8735], dtype=torch.float64)
tensor([0.2192, 0.8017], dtype=torch.float64)
tensor([0.2879, 0.7362], dtype=torch.float64)
tensor([0.3090, 0.7160], dtype=torch.float64)
tensor([0.2436, 0.7776], dtype=torch.float64)
tensor([0.0898, 0.9239], dtype=torch.float64)
tensor([0.0219, 0.9859], dtype=torch.float64)
tensor([-0.0154,  1.0178], dtype=torch.float64)
tensor([-0.0328,  1.0303], dtype=torch.float64)
tensor([-0.0245,  1.0184], dtype=torch.float64)
tensor([0.0113, 0.9816], dtype=torch.float64)
tensor([0.0419, 0.9501], dtype=torch.float64)
tensor([0.0482, 0.9432], dtype=torch.float64)
tensor([0.0827, 0.9098], dtype=torch.float64)
tensor([0.1387, 0.8587], dtype=torch.float64)
tensor([0.2249, 0.7780], dtype=torch.float64)
tensor([0.3553, 0.6568], dtype=torch.float64)
tensor([0.5152, 0.5072], dtype=torch.float64)
tensor([0.6579, 0.3730],

tensor([ 1.1458, -0.1083], dtype=torch.float64)
tensor([ 1.1795, -0.1436], dtype=torch.float64)
tensor([ 1.1891, -0.1548], dtype=torch.float64)
tensor([ 1.1373, -0.1045], dtype=torch.float64)
tensor([ 1.0462, -0.0154], dtype=torch.float64)
tensor([0.8656, 0.1619], dtype=torch.float64)
tensor([0.8318, 0.1940], dtype=torch.float64)
tensor([0.8428, 0.1813], dtype=torch.float64)
tensor([0.7639, 0.2579], dtype=torch.float64)
tensor([0.7186, 0.3026], dtype=torch.float64)
tensor([0.7465, 0.2757], dtype=torch.float64)
tensor([0.8318, 0.1928], dtype=torch.float64)
tensor([0.9174, 0.1096], dtype=torch.float64)
tensor([1.0066, 0.0233], dtype=torch.float64)
tensor([ 1.0827, -0.0508], dtype=torch.float64)
tensor([ 1.0848, -0.0519], dtype=torch.float64)
tensor([ 1.0862, -0.0527], dtype=torch.float64)
tensor([ 1.1146, -0.0804], dtype=torch.float64)
tensor([ 1.0845, -0.0502], dtype=torch.float64)
tensor([ 1.0742, -0.0396], dtype=torch.float64)
tensor([0.8812, 0.1512], dtype=torch.float64)
tensor([0.75

tensor([0.4228, 0.5946], dtype=torch.float64)
tensor([0.3342, 0.6813], dtype=torch.float64)
tensor([0.1949, 0.8171], dtype=torch.float64)
tensor([0.0975, 0.9124], dtype=torch.float64)
tensor([0.0714, 0.9379], dtype=torch.float64)
tensor([0.0305, 0.9769], dtype=torch.float64)
tensor([-0.0637,  1.0672], dtype=torch.float64)
tensor([-0.1162,  1.1162], dtype=torch.float64)
tensor([-0.0911,  1.0912], dtype=torch.float64)
tensor([-0.0749,  1.0749], dtype=torch.float64)
tensor([-0.0448,  1.0456], dtype=torch.float64)
tensor([-0.0158,  1.0183], dtype=torch.float64)
tensor([0.0122, 0.9919], dtype=torch.float64)
tensor([0.0743, 0.9324], dtype=torch.float64)
tensor([0.1487, 0.8617], dtype=torch.float64)
tensor([0.2481, 0.7671], dtype=torch.float64)
tensor([0.3997, 0.6236], dtype=torch.float64)
tensor([0.4982, 0.5301], dtype=torch.float64)
tensor([0.5444, 0.4868], dtype=torch.float64)
tensor([0.5984, 0.4352], dtype=torch.float64)
tensor([0.6447, 0.3901], dtype=torch.float64)
tensor([0.6326, 0.4013

tensor([0.7537, 0.2740], dtype=torch.float64)
tensor([0.7770, 0.2508], dtype=torch.float64)
tensor([0.7964, 0.2312], dtype=torch.float64)
tensor([0.7959, 0.2307], dtype=torch.float64)
tensor([0.8051, 0.2209], dtype=torch.float64)
tensor([0.8118, 0.2134], dtype=torch.float64)
tensor([0.8160, 0.2086], dtype=torch.float64)
tensor([0.8379, 0.1867], dtype=torch.float64)
tensor([0.8718, 0.1532], dtype=torch.float64)
tensor([0.8882, 0.1371], dtype=torch.float64)
tensor([0.8708, 0.1540], dtype=torch.float64)
tensor([0.8294, 0.1948], dtype=torch.float64)
tensor([0.7639, 0.2592], dtype=torch.float64)
tensor([0.6828, 0.3386], dtype=torch.float64)
up correct: 276/816
down correct: 548/847
total correct: 824/1663
omitted: 0/1663
STEP:  2
tensor([0.8560, 0.1776], dtype=torch.float64)
tensor([0.3823, 0.6593], dtype=torch.float64)
tensor([0.1803, 0.8617], dtype=torch.float64)
tensor([0.3116, 0.7217], dtype=torch.float64)
tensor([0.4484, 0.5769], dtype=torch.float64)
tensor([0.6798, 0.3388], dtype=torc

tensor([ 1.0634, -0.0462], dtype=torch.float64)
tensor([ 1.0417, -0.0217], dtype=torch.float64)
tensor([1.0106, 0.0130], dtype=torch.float64)
tensor([0.9642, 0.0613], dtype=torch.float64)
tensor([0.9018, 0.1254], dtype=torch.float64)
tensor([0.4745, 0.5598], dtype=torch.float64)
tensor([0.1170, 0.9188], dtype=torch.float64)
tensor([-0.1478,  1.1770], dtype=torch.float64)
tensor([-0.2267,  1.2447], dtype=torch.float64)
tensor([-0.1409,  1.1451], dtype=torch.float64)
tensor([-0.0924,  1.0859], dtype=torch.float64)
tensor([-0.0500,  1.0346], dtype=torch.float64)
tensor([-0.0256,  1.0027], dtype=torch.float64)
tensor([-0.0509,  1.0258], dtype=torch.float64)
tensor([-0.0518,  1.0267], dtype=torch.float64)
tensor([-0.0608,  1.0371], dtype=torch.float64)
tensor([-0.0448,  1.0220], dtype=torch.float64)
tensor([-0.0398,  1.0189], dtype=torch.float64)
tensor([-0.0137,  0.9934], dtype=torch.float64)
tensor([-0.0268,  1.0086], dtype=torch.float64)
tensor([-0.0189,  1.0023], dtype=torch.float64)
te

tensor([-0.2827,  1.2919], dtype=torch.float64)
tensor([-0.1631,  1.1634], dtype=torch.float64)
tensor([-0.1171,  1.1119], dtype=torch.float64)
tensor([-0.0705,  1.0621], dtype=torch.float64)
tensor([-0.0286,  1.0193], dtype=torch.float64)
tensor([-0.0173,  1.0084], dtype=torch.float64)
tensor([-0.0116,  1.0023], dtype=torch.float64)
tensor([0.0333, 0.9549], dtype=torch.float64)
tensor([-0.0191,  1.0099], dtype=torch.float64)
tensor([-0.0065,  0.9975], dtype=torch.float64)
tensor([0.0248, 0.9638], dtype=torch.float64)
tensor([0.0185, 0.9676], dtype=torch.float64)
tensor([0.0266, 0.9564], dtype=torch.float64)
tensor([0.0948, 0.8827], dtype=torch.float64)
tensor([0.0902, 0.8860], dtype=torch.float64)
tensor([0.0877, 0.8889], dtype=torch.float64)
tensor([0.1617, 0.8141], dtype=torch.float64)
tensor([0.1057, 0.8732], dtype=torch.float64)
tensor([0.0664, 0.9137], dtype=torch.float64)
tensor([-0.0864,  1.0695], dtype=torch.float64)
tensor([0.0173, 0.9581], dtype=torch.float64)
tensor([-0.005

tensor([0.2907, 0.7479], dtype=torch.float64)
tensor([-0.2576,  1.2965], dtype=torch.float64)
tensor([-0.1188,  1.1399], dtype=torch.float64)
tensor([0.0030, 0.9988], dtype=torch.float64)
tensor([-0.0666,  1.0578], dtype=torch.float64)
tensor([-0.0696,  1.0529], dtype=torch.float64)
tensor([-0.1058,  1.0865], dtype=torch.float64)
tensor([-0.0609,  1.0384], dtype=torch.float64)
tensor([-0.0720,  1.0497], dtype=torch.float64)
tensor([-0.0569,  1.0340], dtype=torch.float64)
tensor([-0.0140,  0.9875], dtype=torch.float64)
tensor([-0.0482,  1.0223], dtype=torch.float64)
tensor([0.0211, 0.9500], dtype=torch.float64)
tensor([-0.0053,  0.9802], dtype=torch.float64)
tensor([0.1138, 0.8615], dtype=torch.float64)
tensor([0.5241, 0.4503], dtype=torch.float64)
tensor([ 1.0432, -0.0642], dtype=torch.float64)
tensor([ 1.1645, -0.1742], dtype=torch.float64)
tensor([ 1.2207, -0.2230], dtype=torch.float64)
tensor([ 1.1408, -0.1349], dtype=torch.float64)
tensor([ 1.0994, -0.0864], dtype=torch.float64)
te

tensor([0.8710, 0.1589], dtype=torch.float64)
tensor([0.9639, 0.0670], dtype=torch.float64)
tensor([ 1.0459, -0.0175], dtype=torch.float64)
tensor([ 1.0872, -0.0614], dtype=torch.float64)
tensor([ 1.0643, -0.0381], dtype=torch.float64)
tensor([ 1.0365, -0.0078], dtype=torch.float64)
tensor([ 1.0579, -0.0282], dtype=torch.float64)
tensor([ 1.0484, -0.0173], dtype=torch.float64)
tensor([1.0275, 0.0060], dtype=torch.float64)
tensor([1.0169, 0.0184], dtype=torch.float64)
tensor([0.9991, 0.0375], dtype=torch.float64)
tensor([0.9942, 0.0422], dtype=torch.float64)
tensor([0.7824, 0.2565], dtype=torch.float64)
tensor([0.4757, 0.5656], dtype=torch.float64)
tensor([0.4116, 0.6263], dtype=torch.float64)
tensor([-0.0491,  1.0876], dtype=torch.float64)
tensor([-0.1512,  1.1837], dtype=torch.float64)
tensor([-0.0891,  1.1119], dtype=torch.float64)
tensor([0.0140, 0.9980], dtype=torch.float64)
tensor([0.0198, 0.9844], dtype=torch.float64)
tensor([-0.0341,  1.0340], dtype=torch.float64)
tensor([0.0133

tensor([0.0632, 0.9259], dtype=torch.float64)
tensor([0.2073, 0.7771], dtype=torch.float64)
tensor([0.3814, 0.6010], dtype=torch.float64)
tensor([0.5518, 0.4332], dtype=torch.float64)
tensor([0.2966, 0.6982], dtype=torch.float64)
tensor([0.3407, 0.6572], dtype=torch.float64)
tensor([0.3687, 0.6305], dtype=torch.float64)
tensor([0.4874, 0.5115], dtype=torch.float64)
tensor([0.3925, 0.6080], dtype=torch.float64)
tensor([0.5614, 0.4367], dtype=torch.float64)
tensor([0.9049, 0.0898], dtype=torch.float64)
tensor([0.9610, 0.0360], dtype=torch.float64)
tensor([0.9633, 0.0385], dtype=torch.float64)
tensor([0.9248, 0.0819], dtype=torch.float64)
tensor([0.8882, 0.1220], dtype=torch.float64)
tensor([0.8159, 0.1983], dtype=torch.float64)
tensor([0.8899, 0.1244], dtype=torch.float64)
tensor([0.9155, 0.0976], dtype=torch.float64)
tensor([0.8750, 0.1384], dtype=torch.float64)
tensor([0.8807, 0.1327], dtype=torch.float64)
tensor([0.8955, 0.1173], dtype=torch.float64)
tensor([0.8676, 0.1463], dtype=tor

tensor([0.9065, 0.1450], dtype=torch.float64)
tensor([0.9623, 0.0875], dtype=torch.float64)
tensor([1.0187, 0.0289], dtype=torch.float64)
tensor([ 1.0704, -0.0250], dtype=torch.float64)
tensor([ 1.1152, -0.0722], dtype=torch.float64)
tensor([ 1.1381, -0.0969], dtype=torch.float64)
tensor([ 1.1510, -0.1110], dtype=torch.float64)
tensor([ 1.1537, -0.1147], dtype=torch.float64)
tensor([ 1.1329, -0.0941], dtype=torch.float64)
tensor([ 1.0986, -0.0594], dtype=torch.float64)
tensor([ 1.0434, -0.0032], dtype=torch.float64)
tensor([0.9705, 0.0709], dtype=torch.float64)
tensor([0.8536, 0.1888], dtype=torch.float64)
tensor([0.6800, 0.3637], dtype=torch.float64)
tensor([0.5065, 0.5384], dtype=torch.float64)
tensor([0.2640, 0.7802], dtype=torch.float64)
tensor([7.5334e-04, 1.0426e+00], dtype=torch.float64)
tensor([-0.1816,  1.2241], dtype=torch.float64)
tensor([-0.3599,  1.4001], dtype=torch.float64)
tensor([-0.4306,  1.4701], dtype=torch.float64)
tensor([-0.4006,  1.4400], dtype=torch.float64)
te

tensor([0.9439, 0.1021], dtype=torch.float64)
tensor([0.9134, 0.1329], dtype=torch.float64)
tensor([0.8625, 0.1846], dtype=torch.float64)
tensor([0.7986, 0.2486], dtype=torch.float64)
tensor([0.7527, 0.2948], dtype=torch.float64)
tensor([0.7365, 0.3108], dtype=torch.float64)
tensor([0.7368, 0.3104], dtype=torch.float64)
tensor([0.7632, 0.2842], dtype=torch.float64)
tensor([0.7934, 0.2538], dtype=torch.float64)
tensor([0.8228, 0.2241], dtype=torch.float64)
tensor([0.8609, 0.1858], dtype=torch.float64)
tensor([0.9055, 0.1407], dtype=torch.float64)
tensor([0.9375, 0.1081], dtype=torch.float64)
tensor([0.9500, 0.0954], dtype=torch.float64)
tensor([0.9830, 0.0623], dtype=torch.float64)
tensor([1.0293, 0.0154], dtype=torch.float64)
tensor([ 1.0765, -0.0327], dtype=torch.float64)
tensor([ 1.1399, -0.0973], dtype=torch.float64)
tensor([ 1.2128, -0.1726], dtype=torch.float64)
tensor([ 1.2894, -0.2520], dtype=torch.float64)
tensor([ 1.3621, -0.3280], dtype=torch.float64)
tensor([ 1.4125, -0.3814

tensor([0.8466, 0.2004], dtype=torch.float64)
tensor([0.9423, 0.1027], dtype=torch.float64)
tensor([1.0227, 0.0199], dtype=torch.float64)
tensor([ 1.0816, -0.0411], dtype=torch.float64)
tensor([ 1.1421, -0.1040], dtype=torch.float64)
tensor([ 1.1955, -0.1600], dtype=torch.float64)
tensor([ 1.2376, -0.2045], dtype=torch.float64)
tensor([ 1.2544, -0.2230], dtype=torch.float64)
tensor([ 1.2510, -0.2201], dtype=torch.float64)
tensor([ 1.2472, -0.2164], dtype=torch.float64)
tensor([ 1.2313, -0.2002], dtype=torch.float64)
tensor([ 1.1926, -0.1602], dtype=torch.float64)
tensor([ 1.1443, -0.1100], dtype=torch.float64)
tensor([ 1.0972, -0.0607], dtype=torch.float64)
tensor([ 1.0426, -0.0039], dtype=torch.float64)
tensor([1.0070, 0.0341], dtype=torch.float64)
tensor([1.0074, 0.0355], dtype=torch.float64)
tensor([1.0321, 0.0116], dtype=torch.float64)
tensor([ 1.0484, -0.0041], dtype=torch.float64)
tensor([ 1.0582, -0.0131], dtype=torch.float64)
tensor([ 1.0794, -0.0340], dtype=torch.float64)
tens

tensor([0.7097, 0.3387], dtype=torch.float64)
tensor([0.6734, 0.3753], dtype=torch.float64)
tensor([0.6326, 0.4162], dtype=torch.float64)
tensor([0.5661, 0.4828], dtype=torch.float64)
tensor([0.4680, 0.5809], dtype=torch.float64)
tensor([0.3871, 0.6619], dtype=torch.float64)
tensor([0.3447, 0.7041], dtype=torch.float64)
tensor([0.3414, 0.7073], dtype=torch.float64)
tensor([0.3522, 0.6965], dtype=torch.float64)
tensor([0.4573, 0.5919], dtype=torch.float64)
tensor([0.5652, 0.4838], dtype=torch.float64)
tensor([0.6696, 0.3794], dtype=torch.float64)
tensor([0.7585, 0.2900], dtype=torch.float64)
tensor([0.8105, 0.2374], dtype=torch.float64)
tensor([0.8297, 0.2178], dtype=torch.float64)
tensor([0.8223, 0.2250], dtype=torch.float64)
tensor([0.8178, 0.2295], dtype=torch.float64)
tensor([0.8170, 0.2300], dtype=torch.float64)
tensor([0.8214, 0.2254], dtype=torch.float64)
tensor([0.8089, 0.2377], dtype=torch.float64)
tensor([0.7986, 0.2484], dtype=torch.float64)
tensor([0.7850, 0.2620], dtype=tor

tensor([0.8400, 0.2090], dtype=torch.float64)
tensor([0.8140, 0.2347], dtype=torch.float64)
tensor([0.7910, 0.2576], dtype=torch.float64)
tensor([0.7797, 0.2687], dtype=torch.float64)
tensor([0.7873, 0.2608], dtype=torch.float64)
tensor([0.8197, 0.2278], dtype=torch.float64)
tensor([0.8713, 0.1752], dtype=torch.float64)
tensor([0.9378, 0.1073], dtype=torch.float64)
tensor([0.9891, 0.0543], dtype=torch.float64)
tensor([1.0115, 0.0307], dtype=torch.float64)
tensor([1.0171, 0.0242], dtype=torch.float64)
tensor([1.0239, 0.0168], dtype=torch.float64)
tensor([1.0345, 0.0056], dtype=torch.float64)
tensor([1.0280, 0.0116], dtype=torch.float64)
tensor([1.0185, 0.0210], dtype=torch.float64)
tensor([1.0229, 0.0167], dtype=torch.float64)
tensor([ 1.0439, -0.0045], dtype=torch.float64)
tensor([ 1.0613, -0.0222], dtype=torch.float64)
tensor([ 1.0832, -0.0443], dtype=torch.float64)
tensor([ 1.0706, -0.0316], dtype=torch.float64)
tensor([ 1.0417, -0.0016], dtype=torch.float64)
tensor([0.9868, 0.0545],

tensor([0.8196, 0.2206], dtype=torch.float64)
tensor([0.8529, 0.1865], dtype=torch.float64)
tensor([0.7270, 0.3005], dtype=torch.float64)
tensor([0.5759, 0.4380], dtype=torch.float64)
tensor([0.4479, 0.5532], dtype=torch.float64)
tensor([0.2680, 0.7167], dtype=torch.float64)
tensor([0.1173, 0.8522], dtype=torch.float64)
tensor([-0.1722,  1.1137], dtype=torch.float64)
tensor([-0.3013,  1.2264], dtype=torch.float64)
tensor([-0.3206,  1.2406], dtype=torch.float64)
tensor([-0.4203,  1.3306], dtype=torch.float64)
tensor([-0.4325,  1.3408], dtype=torch.float64)
tensor([-0.2997,  1.2234], dtype=torch.float64)
tensor([-0.3374,  1.2636], dtype=torch.float64)
tensor([-0.2333,  1.1733], dtype=torch.float64)
tensor([-0.1429,  1.0974], dtype=torch.float64)
tensor([-0.0900,  1.0554], dtype=torch.float64)
tensor([0.1723, 0.8230], dtype=torch.float64)
tensor([0.2745, 0.7407], dtype=torch.float64)
tensor([0.5561, 0.4918], dtype=torch.float64)
tensor([0.6666, 0.3998], dtype=torch.float64)
tensor([0.9674

tensor([0.7894, 0.2580], dtype=torch.float64)
tensor([0.9872, 0.0759], dtype=torch.float64)
tensor([0.9926, 0.0729], dtype=torch.float64)
tensor([ 1.1817, -0.1040], dtype=torch.float64)
tensor([ 1.2304, -0.1525], dtype=torch.float64)
tensor([ 1.3100, -0.2328], dtype=torch.float64)
tensor([ 1.4055, -0.3273], dtype=torch.float64)
tensor([ 1.3210, -0.2533], dtype=torch.float64)
tensor([ 1.3069, -0.2476], dtype=torch.float64)
tensor([ 1.5313, -0.4631], dtype=torch.float64)
tensor([ 1.5143, -0.4504], dtype=torch.float64)
tensor([ 1.2959, -0.2514], dtype=torch.float64)
tensor([ 1.1336, -0.1054], dtype=torch.float64)
tensor([ 1.1957, -0.1665], dtype=torch.float64)
tensor([ 1.3210, -0.2817], dtype=torch.float64)
tensor([ 1.2667, -0.2284], dtype=torch.float64)
tensor([ 1.0980, -0.0700], dtype=torch.float64)
tensor([ 1.0431, -0.0179], dtype=torch.float64)
tensor([0.9514, 0.0734], dtype=torch.float64)
tensor([0.8445, 0.1805], dtype=torch.float64)
tensor([0.6136, 0.4000], dtype=torch.float64)
tens

tensor([0.5437, 0.4681], dtype=torch.float64)
tensor([0.5136, 0.5000], dtype=torch.float64)
tensor([0.6268, 0.3940], dtype=torch.float64)
tensor([0.7174, 0.3077], dtype=torch.float64)
tensor([0.7920, 0.2353], dtype=torch.float64)
tensor([0.9111, 0.1214], dtype=torch.float64)
tensor([0.8786, 0.1500], dtype=torch.float64)
tensor([0.9235, 0.1061], dtype=torch.float64)
tensor([0.9549, 0.0747], dtype=torch.float64)
tensor([0.9105, 0.1141], dtype=torch.float64)
tensor([0.8657, 0.1526], dtype=torch.float64)
tensor([0.7838, 0.2248], dtype=torch.float64)
tensor([0.8269, 0.1824], dtype=torch.float64)
tensor([0.8037, 0.2041], dtype=torch.float64)
tensor([0.7239, 0.2800], dtype=torch.float64)
tensor([0.7736, 0.2358], dtype=torch.float64)
tensor([0.6911, 0.3152], dtype=torch.float64)
tensor([0.5197, 0.4772], dtype=torch.float64)
tensor([0.5523, 0.4486], dtype=torch.float64)
tensor([0.5330, 0.4695], dtype=torch.float64)
tensor([0.5037, 0.4989], dtype=torch.float64)
tensor([0.3506, 0.6411], dtype=tor

tensor([0.7326, 0.2914], dtype=torch.float64)
tensor([0.7381, 0.2843], dtype=torch.float64)
tensor([0.6421, 0.3709], dtype=torch.float64)
tensor([0.5038, 0.4964], dtype=torch.float64)
tensor([0.4043, 0.5871], dtype=torch.float64)
tensor([0.4251, 0.5685], dtype=torch.float64)
tensor([0.6101, 0.4011], dtype=torch.float64)
tensor([0.4768, 0.5294], dtype=torch.float64)
tensor([0.3251, 0.6690], dtype=torch.float64)
tensor([0.4285, 0.5726], dtype=torch.float64)
tensor([0.4346, 0.5699], dtype=torch.float64)
tensor([0.5492, 0.4663], dtype=torch.float64)
tensor([0.6104, 0.4130], dtype=torch.float64)
tensor([0.5619, 0.4579], dtype=torch.float64)
tensor([0.5992, 0.4201], dtype=torch.float64)
tensor([0.5689, 0.4450], dtype=torch.float64)
tensor([0.4526, 0.5491], dtype=torch.float64)
tensor([0.3445, 0.6445], dtype=torch.float64)
tensor([0.3829, 0.6061], dtype=torch.float64)
tensor([0.3450, 0.6427], dtype=torch.float64)
tensor([0.4039, 0.5908], dtype=torch.float64)
tensor([0.4271, 0.5753], dtype=tor

tensor([0.5500, 0.4731], dtype=torch.float64)
tensor([0.5635, 0.4571], dtype=torch.float64)
tensor([0.4394, 0.5693], dtype=torch.float64)
tensor([0.4041, 0.5984], dtype=torch.float64)
tensor([0.4416, 0.5617], dtype=torch.float64)
tensor([0.5930, 0.4216], dtype=torch.float64)
tensor([0.6230, 0.3953], dtype=torch.float64)
tensor([0.7087, 0.3141], dtype=torch.float64)
tensor([0.6538, 0.3639], dtype=torch.float64)
tensor([0.6651, 0.3507], dtype=torch.float64)
tensor([0.6186, 0.3921], dtype=torch.float64)
tensor([0.5790, 0.4270], dtype=torch.float64)
tensor([0.5766, 0.4281], dtype=torch.float64)
tensor([0.5185, 0.4831], dtype=torch.float64)
tensor([0.6484, 0.3645], dtype=torch.float64)
tensor([0.7066, 0.3161], dtype=torch.float64)
tensor([0.9169, 0.1269], dtype=torch.float64)
tensor([0.9546, 0.0988], dtype=torch.float64)
tensor([0.9572, 0.0985], dtype=torch.float64)
tensor([0.8849, 0.1649], dtype=torch.float64)
tensor([0.8409, 0.2037], dtype=torch.float64)
tensor([0.8358, 0.2064], dtype=tor

tensor([0.0879, 0.8781], dtype=torch.float64)
tensor([0.0673, 0.8977], dtype=torch.float64)
tensor([0.0490, 0.9154], dtype=torch.float64)
tensor([0.0310, 0.9293], dtype=torch.float64)
tensor([0.0163, 0.9422], dtype=torch.float64)
tensor([0.2819, 0.6748], dtype=torch.float64)
tensor([0.5561, 0.4081], dtype=torch.float64)
tensor([ 1.1297, -0.1506], dtype=torch.float64)
tensor([ 1.1580, -0.1563], dtype=torch.float64)
tensor([ 1.0772, -0.0610], dtype=torch.float64)
tensor([ 1.0793, -0.0540], dtype=torch.float64)
tensor([ 1.0487, -0.0213], dtype=torch.float64)
tensor([0.9509, 0.0749], dtype=torch.float64)
tensor([0.8771, 0.1496], dtype=torch.float64)
tensor([1.0127, 0.0106], dtype=torch.float64)
tensor([0.9927, 0.0293], dtype=torch.float64)
tensor([1.0117, 0.0111], dtype=torch.float64)
tensor([0.8482, 0.1753], dtype=torch.float64)
tensor([0.6328, 0.3893], dtype=torch.float64)
tensor([0.5695, 0.4464], dtype=torch.float64)
tensor([ 1.0599, -0.0512], dtype=torch.float64)
tensor([1.0123, 0.0023

tensor([1.0129, 0.0167], dtype=torch.float64)
tensor([0.9891, 0.0440], dtype=torch.float64)
tensor([0.9694, 0.0627], dtype=torch.float64)
tensor([0.9753, 0.0536], dtype=torch.float64)
tensor([0.9872, 0.0401], dtype=torch.float64)
tensor([0.9986, 0.0291], dtype=torch.float64)
tensor([0.9947, 0.0342], dtype=torch.float64)
tensor([0.9922, 0.0354], dtype=torch.float64)
tensor([0.9970, 0.0290], dtype=torch.float64)
tensor([1.0071, 0.0191], dtype=torch.float64)
tensor([1.0000, 0.0268], dtype=torch.float64)
tensor([0.9886, 0.0383], dtype=torch.float64)
tensor([0.9260, 0.0994], dtype=torch.float64)
tensor([0.9662, 0.0603], dtype=torch.float64)
tensor([0.9081, 0.1183], dtype=torch.float64)
tensor([0.4642, 0.5612], dtype=torch.float64)
tensor([0.8650, 0.1511], dtype=torch.float64)
tensor([ 1.0665, -0.0504], dtype=torch.float64)
tensor([ 1.0854, -0.0639], dtype=torch.float64)
tensor([ 1.0450, -0.0207], dtype=torch.float64)
tensor([0.9585, 0.0669], dtype=torch.float64)
tensor([1.0133, 0.0129], dty

tensor([0.2897, 0.6757], dtype=torch.float64)
tensor([0.6740, 0.2976], dtype=torch.float64)
tensor([0.8778, 0.1035], dtype=torch.float64)
tensor([ 1.0122, -0.0205], dtype=torch.float64)
tensor([ 1.1183, -0.1178], dtype=torch.float64)
tensor([ 1.0727, -0.0647], dtype=torch.float64)
tensor([ 1.0880, -0.0753], dtype=torch.float64)
tensor([ 1.0850, -0.0702], dtype=torch.float64)
tensor([ 1.0611, -0.0447], dtype=torch.float64)
tensor([ 1.0466, -0.0296], dtype=torch.float64)
tensor([1.0141, 0.0026], dtype=torch.float64)
tensor([ 1.0449, -0.0284], dtype=torch.float64)
tensor([ 1.0261, -0.0102], dtype=torch.float64)
tensor([0.9791, 0.0373], dtype=torch.float64)
tensor([1.0116, 0.0045], dtype=torch.float64)
tensor([0.9370, 0.0788], dtype=torch.float64)
tensor([0.7328, 0.2835], dtype=torch.float64)
tensor([0.7675, 0.2446], dtype=torch.float64)
tensor([0.6746, 0.3338], dtype=torch.float64)
tensor([0.5965, 0.4085], dtype=torch.float64)
tensor([0.2188, 0.7815], dtype=torch.float64)
tensor([0.1252, 

tensor([0.8453, 0.1492], dtype=torch.float64)
tensor([0.9465, 0.0526], dtype=torch.float64)
tensor([0.9566, 0.0476], dtype=torch.float64)
tensor([0.8383, 0.1692], dtype=torch.float64)
tensor([0.6131, 0.3944], dtype=torch.float64)
tensor([0.4115, 0.5913], dtype=torch.float64)
tensor([0.4441, 0.5514], dtype=torch.float64)
tensor([0.7932, 0.1981], dtype=torch.float64)
tensor([0.4260, 0.5691], dtype=torch.float64)
tensor([0.1324, 0.8602], dtype=torch.float64)
tensor([0.4149, 0.5701], dtype=torch.float64)
tensor([0.3529, 0.6309], dtype=torch.float64)
tensor([0.6180, 0.3659], dtype=torch.float64)
tensor([0.7149, 0.2738], dtype=torch.float64)
tensor([0.6050, 0.3888], dtype=torch.float64)
tensor([0.7208, 0.2745], dtype=torch.float64)
tensor([0.6615, 0.3356], dtype=torch.float64)
tensor([0.4312, 0.5657], dtype=torch.float64)
tensor([0.2129, 0.7791], dtype=torch.float64)
tensor([0.3243, 0.6604], dtype=torch.float64)
tensor([0.2138, 0.7677], dtype=torch.float64)
tensor([0.3442, 0.6345], dtype=tor

tensor([0.6031, 0.3957], dtype=torch.float64)
tensor([0.6652, 0.3333], dtype=torch.float64)
tensor([0.3841, 0.6138], dtype=torch.float64)
tensor([0.3494, 0.6436], dtype=torch.float64)
tensor([0.4215, 0.5667], dtype=torch.float64)
tensor([0.7339, 0.2529], dtype=torch.float64)
tensor([0.7453, 0.2465], dtype=torch.float64)
tensor([0.9040, 0.0919], dtype=torch.float64)
tensor([0.8276, 0.1739], dtype=torch.float64)
tensor([0.8730, 0.1307], dtype=torch.float64)
tensor([0.8056, 0.1997], dtype=torch.float64)
tensor([0.7493, 0.2558], dtype=torch.float64)
tensor([0.7506, 0.2529], dtype=torch.float64)
tensor([0.6468, 0.3560], dtype=torch.float64)
tensor([0.8772, 0.1232], dtype=torch.float64)
tensor([0.9161, 0.0876], dtype=torch.float64)
tensor([ 1.0797, -0.0716], dtype=torch.float64)
tensor([ 1.0606, -0.0465], dtype=torch.float64)
tensor([ 1.0503, -0.0318], dtype=torch.float64)
tensor([1.0194, 0.0013], dtype=torch.float64)
tensor([1.0051, 0.0170], dtype=torch.float64)
tensor([1.0047, 0.0175], dty

tensor([0.3664, 0.5409], dtype=torch.float64)
tensor([0.3618, 0.5433], dtype=torch.float64)
tensor([0.3629, 0.5411], dtype=torch.float64)
tensor([0.3663, 0.5374], dtype=torch.float64)
tensor([0.3753, 0.5289], dtype=torch.float64)
tensor([0.3863, 0.5192], dtype=torch.float64)
tensor([0.4007, 0.5067], dtype=torch.float64)
tensor([0.4179, 0.4921], dtype=torch.float64)
tensor([0.4419, 0.4720], dtype=torch.float64)
tensor([0.4718, 0.4473], dtype=torch.float64)
tensor([0.4939, 0.4301], dtype=torch.float64)
tensor([0.5143, 0.4142], dtype=torch.float64)
tensor([0.5322, 0.4007], dtype=torch.float64)
tensor([0.5387, 0.3979], dtype=torch.float64)
tensor([0.5365, 0.4022], dtype=torch.float64)
tensor([0.5384, 0.4017], dtype=torch.float64)
tensor([0.5395, 0.4016], dtype=torch.float64)
tensor([0.5394, 0.4022], dtype=torch.float64)
tensor([0.5306, 0.4103], dtype=torch.float64)
tensor([0.5185, 0.4208], dtype=torch.float64)
tensor([0.5064, 0.4308], dtype=torch.float64)
tensor([0.5057, 0.4300], dtype=tor

tensor([0.7306, 0.2541], dtype=torch.float64)
tensor([0.7428, 0.2486], dtype=torch.float64)
tensor([0.7386, 0.2567], dtype=torch.float64)
tensor([0.7305, 0.2660], dtype=torch.float64)
tensor([0.7245, 0.2715], dtype=torch.float64)
tensor([0.7202, 0.2750], dtype=torch.float64)
tensor([0.7083, 0.2854], dtype=torch.float64)
tensor([0.6900, 0.3006], dtype=torch.float64)
tensor([0.6616, 0.3235], dtype=torch.float64)
tensor([0.6283, 0.3494], dtype=torch.float64)
tensor([0.5953, 0.3742], dtype=torch.float64)
tensor([0.5689, 0.3927], dtype=torch.float64)
tensor([0.5441, 0.4099], dtype=torch.float64)
tensor([0.5160, 0.4302], dtype=torch.float64)
tensor([0.4995, 0.4404], dtype=torch.float64)
tensor([0.4985, 0.4376], dtype=torch.float64)
tensor([0.5131, 0.4227], dtype=torch.float64)
tensor([0.5285, 0.4087], dtype=torch.float64)
tensor([0.5337, 0.4050], dtype=torch.float64)
tensor([0.5395, 0.4007], dtype=torch.float64)
tensor([0.5479, 0.3943], dtype=torch.float64)
tensor([0.5515, 0.3927], dtype=tor

tensor([0.4532, 0.4777], dtype=torch.float64)
tensor([0.4462, 0.4821], dtype=torch.float64)
tensor([0.4462, 0.4804], dtype=torch.float64)
tensor([0.4495, 0.4763], dtype=torch.float64)
tensor([0.4632, 0.4637], dtype=torch.float64)
tensor([0.4788, 0.4503], dtype=torch.float64)
tensor([0.4948, 0.4371], dtype=torch.float64)
tensor([0.5136, 0.4218], dtype=torch.float64)
tensor([0.5333, 0.4062], dtype=torch.float64)
tensor([0.5541, 0.3900], dtype=torch.float64)
tensor([0.5693, 0.3791], dtype=torch.float64)
tensor([0.5808, 0.3712], dtype=torch.float64)
tensor([0.5929, 0.3625], dtype=torch.float64)
tensor([0.6012, 0.3573], dtype=torch.float64)
tensor([0.6072, 0.3540], dtype=torch.float64)
tensor([0.6104, 0.3529], dtype=torch.float64)
tensor([0.6107, 0.3538], dtype=torch.float64)
tensor([0.6091, 0.3560], dtype=torch.float64)
tensor([0.6009, 0.3635], dtype=torch.float64)
tensor([0.5925, 0.3703], dtype=torch.float64)
tensor([0.5838, 0.3772], dtype=torch.float64)
tensor([0.5678, 0.3902], dtype=tor

tensor([0.4305, 0.4902], dtype=torch.float64)
tensor([0.4395, 0.4820], dtype=torch.float64)
tensor([0.4480, 0.4750], dtype=torch.float64)
tensor([0.4588, 0.4660], dtype=torch.float64)
tensor([0.4717, 0.4555], dtype=torch.float64)
tensor([0.4818, 0.4478], dtype=torch.float64)
tensor([0.4917, 0.4403], dtype=torch.float64)
tensor([0.5026, 0.4322], dtype=torch.float64)
tensor([0.5141, 0.4234], dtype=torch.float64)
tensor([0.5238, 0.4163], dtype=torch.float64)
tensor([0.5370, 0.4061], dtype=torch.float64)
tensor([0.5478, 0.3984], dtype=torch.float64)
tensor([0.5531, 0.3955], dtype=torch.float64)
tensor([0.5505, 0.3993], dtype=torch.float64)
tensor([0.5407, 0.4087], dtype=torch.float64)
tensor([0.5300, 0.4178], dtype=torch.float64)
tensor([0.5253, 0.4209], dtype=torch.float64)
tensor([0.5207, 0.4242], dtype=torch.float64)
tensor([0.5137, 0.4298], dtype=torch.float64)
tensor([0.5085, 0.4336], dtype=torch.float64)
tensor([0.5048, 0.4360], dtype=torch.float64)
tensor([0.5049, 0.4351], dtype=tor

tensor([0.5128, 0.4260], dtype=torch.float64)
tensor([0.5106, 0.4286], dtype=torch.float64)
tensor([0.5094, 0.4299], dtype=torch.float64)
tensor([0.5129, 0.4268], dtype=torch.float64)
tensor([0.5191, 0.4216], dtype=torch.float64)
tensor([0.5300, 0.4125], dtype=torch.float64)
tensor([0.5378, 0.4067], dtype=torch.float64)
tensor([0.5439, 0.4024], dtype=torch.float64)
tensor([0.5466, 0.4009], dtype=torch.float64)
tensor([0.5465, 0.4018], dtype=torch.float64)
tensor([0.5450, 0.4036], dtype=torch.float64)
tensor([0.5392, 0.4087], dtype=torch.float64)
tensor([0.5359, 0.4111], dtype=torch.float64)
tensor([0.5337, 0.4124], dtype=torch.float64)
tensor([0.5367, 0.4090], dtype=torch.float64)
tensor([0.5417, 0.4042], dtype=torch.float64)
tensor([0.5487, 0.3981], dtype=torch.float64)
tensor([0.5542, 0.3937], dtype=torch.float64)
tensor([0.5566, 0.3923], dtype=torch.float64)
tensor([0.5579, 0.3916], dtype=torch.float64)
tensor([0.5645, 0.3861], dtype=torch.float64)
tensor([0.5741, 0.3779], dtype=tor

tensor([-0.2695,  1.2635], dtype=torch.float64)
tensor([-0.1970,  1.1903], dtype=torch.float64)
tensor([-0.1387,  1.1310], dtype=torch.float64)
tensor([0.0357, 0.9518], dtype=torch.float64)
tensor([0.1597, 0.8253], dtype=torch.float64)
tensor([0.3593, 0.6207], dtype=torch.float64)
tensor([0.4974, 0.4814], dtype=torch.float64)
tensor([0.7121, 0.2642], dtype=torch.float64)
tensor([0.8840, 0.0915], dtype=torch.float64)
tensor([0.9151, 0.0600], dtype=torch.float64)
tensor([ 1.0056, -0.0336], dtype=torch.float64)
tensor([ 1.0298, -0.0587], dtype=torch.float64)
tensor([0.8851, 0.0897], dtype=torch.float64)
tensor([0.7803, 0.1957], dtype=torch.float64)
tensor([0.8345, 0.1396], dtype=torch.float64)
tensor([0.8460, 0.1279], dtype=torch.float64)
tensor([0.8705, 0.1021], dtype=torch.float64)
tensor([0.7682, 0.2052], dtype=torch.float64)
tensor([0.6599, 0.3146], dtype=torch.float64)
tensor([0.6078, 0.3664], dtype=torch.float64)
tensor([0.7710, 0.1997], dtype=torch.float64)
tensor([0.8269, 0.1439],

tensor([0.8666, 0.1031], dtype=torch.float64)
tensor([0.8376, 0.1306], dtype=torch.float64)
tensor([0.7825, 0.1846], dtype=torch.float64)
tensor([0.5982, 0.3701], dtype=torch.float64)
tensor([0.6467, 0.3191], dtype=torch.float64)
tensor([0.8093, 0.1553], dtype=torch.float64)
tensor([ 0.9668, -0.0012], dtype=torch.float64)
tensor([ 0.9840, -0.0156], dtype=torch.float64)
tensor([0.8712, 0.1011], dtype=torch.float64)
tensor([0.8771, 0.0954], dtype=torch.float64)
tensor([0.8796, 0.0943], dtype=torch.float64)
tensor([0.7580, 0.2213], dtype=torch.float64)
tensor([0.6465, 0.3368], dtype=torch.float64)
tensor([0.6842, 0.2995], dtype=torch.float64)
tensor([0.7441, 0.2401], dtype=torch.float64)
tensor([0.7037, 0.2849], dtype=torch.float64)
tensor([0.6344, 0.3585], dtype=torch.float64)
tensor([0.5749, 0.4213], dtype=torch.float64)
tensor([0.3352, 0.6678], dtype=torch.float64)
tensor([0.1851, 0.8206], dtype=torch.float64)
tensor([0.0866, 0.9202], dtype=torch.float64)
tensor([0.0949, 0.9103], dtype

tensor([0.6075, 0.3756], dtype=torch.float64)
tensor([0.5136, 0.4720], dtype=torch.float64)
tensor([0.4442, 0.5424], dtype=torch.float64)
tensor([0.3843, 0.6045], dtype=torch.float64)
tensor([0.3129, 0.6769], dtype=torch.float64)
tensor([0.2926, 0.6961], dtype=torch.float64)
tensor([0.2584, 0.7308], dtype=torch.float64)
tensor([0.2693, 0.7188], dtype=torch.float64)
tensor([0.1881, 0.8019], dtype=torch.float64)
tensor([0.1849, 0.8048], dtype=torch.float64)
tensor([0.2641, 0.7268], dtype=torch.float64)
tensor([0.3583, 0.6348], dtype=torch.float64)
tensor([0.3882, 0.6081], dtype=torch.float64)
tensor([0.2938, 0.7065], dtype=torch.float64)
tensor([0.2560, 0.7463], dtype=torch.float64)
tensor([0.2742, 0.7275], dtype=torch.float64)
tensor([0.2900, 0.7123], dtype=torch.float64)
tensor([0.2819, 0.7213], dtype=torch.float64)
tensor([0.2708, 0.7333], dtype=torch.float64)
tensor([0.2573, 0.7476], dtype=torch.float64)
tensor([0.2385, 0.7670], dtype=torch.float64)
tensor([0.1935, 0.8129], dtype=tor

tensor([0.4601, 0.5336], dtype=torch.float64)
tensor([0.4556, 0.5374], dtype=torch.float64)
tensor([0.4286, 0.5635], dtype=torch.float64)
tensor([0.4474, 0.5426], dtype=torch.float64)
tensor([0.4618, 0.5259], dtype=torch.float64)
tensor([0.5093, 0.4744], dtype=torch.float64)
tensor([0.5362, 0.4461], dtype=torch.float64)
tensor([0.4908, 0.4913], dtype=torch.float64)
tensor([0.4435, 0.5384], dtype=torch.float64)
tensor([0.4380, 0.5439], dtype=torch.float64)
tensor([0.6163, 0.3624], dtype=torch.float64)
tensor([0.7161, 0.2627], dtype=torch.float64)
tensor([0.7825, 0.1958], dtype=torch.float64)
tensor([0.8311, 0.1469], dtype=torch.float64)
tensor([0.8802, 0.0974], dtype=torch.float64)
tensor([0.8772, 0.1008], dtype=torch.float64)
tensor([0.8834, 0.0944], dtype=torch.float64)
tensor([0.8195, 0.1600], dtype=torch.float64)
tensor([0.8359, 0.1431], dtype=torch.float64)
tensor([0.8562, 0.1231], dtype=torch.float64)
tensor([0.8464, 0.1325], dtype=torch.float64)
tensor([0.8874, 0.0894], dtype=tor

STEP:  2
tensor([0.2346, 0.7691], dtype=torch.float64)
tensor([0.1974, 0.8003], dtype=torch.float64)
tensor([0.3236, 0.6707], dtype=torch.float64)
tensor([0.4076, 0.5820], dtype=torch.float64)
tensor([0.7973, 0.2016], dtype=torch.float64)
tensor([ 1.0900, -0.0799], dtype=torch.float64)
tensor([ 1.0978, -0.0813], dtype=torch.float64)
tensor([ 1.1123, -0.0930], dtype=torch.float64)
tensor([ 1.1272, -0.1072], dtype=torch.float64)
tensor([ 1.1300, -0.1104], dtype=torch.float64)
tensor([ 1.2015, -0.1839], dtype=torch.float64)
tensor([ 1.2404, -0.2241], dtype=torch.float64)
tensor([ 1.1750, -0.1572], dtype=torch.float64)
tensor([ 1.0455, -0.0254], dtype=torch.float64)
tensor([0.9842, 0.0357], dtype=torch.float64)
tensor([0.8964, 0.1226], dtype=torch.float64)
tensor([0.9621, 0.0543], dtype=torch.float64)
tensor([ 1.0167, -0.0018], dtype=torch.float64)
tensor([0.8138, 0.1983], dtype=torch.float64)
tensor([0.4721, 0.5227], dtype=torch.float64)
tensor([0.5487, 0.4352], dtype=torch.float64)
tenso

tensor([-0.1352,  1.0641], dtype=torch.float64)
tensor([-0.1077,  1.0379], dtype=torch.float64)
tensor([-0.0948,  1.0271], dtype=torch.float64)
tensor([-0.0867,  1.0204], dtype=torch.float64)
tensor([0.0055, 0.9296], dtype=torch.float64)
tensor([0.0560, 0.8821], dtype=torch.float64)
tensor([0.2212, 0.7207], dtype=torch.float64)
tensor([0.3737, 0.5786], dtype=torch.float64)
tensor([0.7933, 0.1804], dtype=torch.float64)
tensor([ 1.1411, -0.1407], dtype=torch.float64)
tensor([ 1.0890, -0.0767], dtype=torch.float64)
tensor([ 1.1793, -0.1619], dtype=torch.float64)
tensor([ 1.1242, -0.1037], dtype=torch.float64)
tensor([0.8377, 0.1824], dtype=torch.float64)
tensor([0.7130, 0.2997], dtype=torch.float64)
tensor([0.8888, 0.1218], dtype=torch.float64)
tensor([0.9079, 0.1017], dtype=torch.float64)
tensor([0.9522, 0.0557], dtype=torch.float64)
tensor([0.7364, 0.2633], dtype=torch.float64)
tensor([0.5428, 0.4454], dtype=torch.float64)
tensor([0.4551, 0.5215], dtype=torch.float64)
tensor([0.8595, 0.

tensor([0.9068, 0.1107], dtype=torch.float64)
tensor([0.8445, 0.1748], dtype=torch.float64)
tensor([0.8810, 0.1377], dtype=torch.float64)
tensor([0.9147, 0.1026], dtype=torch.float64)
tensor([0.9258, 0.0872], dtype=torch.float64)
tensor([0.7966, 0.2101], dtype=torch.float64)
tensor([0.8505, 0.1487], dtype=torch.float64)
tensor([0.7573, 0.2306], dtype=torch.float64)
tensor([0.3605, 0.6041], dtype=torch.float64)
tensor([0.5328, 0.4262], dtype=torch.float64)
tensor([0.9407, 0.0331], dtype=torch.float64)
tensor([ 1.2159, -0.2210], dtype=torch.float64)
tensor([ 1.1256, -0.1174], dtype=torch.float64)
tensor([0.8698, 0.1417], dtype=torch.float64)
tensor([0.9292, 0.0828], dtype=torch.float64)
tensor([0.9428, 0.0710], dtype=torch.float64)
tensor([0.7410, 0.2738], dtype=torch.float64)
tensor([0.5968, 0.4152], dtype=torch.float64)
tensor([0.7260, 0.2871], dtype=torch.float64)
tensor([0.8322, 0.1844], dtype=torch.float64)
tensor([0.7450, 0.2764], dtype=torch.float64)
tensor([0.6341, 0.3903], dtype

tensor([0.8539, 0.1661], dtype=torch.float64)
tensor([0.8942, 0.1232], dtype=torch.float64)
tensor([0.8321, 0.1837], dtype=torch.float64)
tensor([0.6684, 0.3401], dtype=torch.float64)
tensor([0.6592, 0.3429], dtype=torch.float64)
tensor([0.6252, 0.3737], dtype=torch.float64)
tensor([0.5763, 0.4191], dtype=torch.float64)
tensor([0.3895, 0.5991], dtype=torch.float64)
tensor([0.2523, 0.7260], dtype=torch.float64)
tensor([0.1771, 0.7968], dtype=torch.float64)
tensor([0.0489, 0.9155], dtype=torch.float64)
tensor([0.0287, 0.9277], dtype=torch.float64)
tensor([0.0034, 0.9497], dtype=torch.float64)
tensor([0.0402, 0.9105], dtype=torch.float64)
tensor([-0.0485,  0.9970], dtype=torch.float64)
tensor([-0.0237,  0.9711], dtype=torch.float64)
tensor([0.1206, 0.8356], dtype=torch.float64)
tensor([0.3082, 0.6633], dtype=torch.float64)
tensor([0.3753, 0.6099], dtype=torch.float64)
tensor([0.1604, 0.8250], dtype=torch.float64)
tensor([0.0961, 0.8888], dtype=torch.float64)
tensor([0.1238, 0.8598], dtype

tensor([0.8553, 0.1644], dtype=torch.float64)
tensor([0.7694, 0.2500], dtype=torch.float64)
tensor([0.6234, 0.3908], dtype=torch.float64)
tensor([0.4691, 0.5333], dtype=torch.float64)
tensor([0.4360, 0.5567], dtype=torch.float64)
tensor([0.6259, 0.3671], dtype=torch.float64)
tensor([0.5203, 0.4715], dtype=torch.float64)
tensor([0.3293, 0.6554], dtype=torch.float64)
tensor([0.3897, 0.5910], dtype=torch.float64)
tensor([0.4043, 0.5759], dtype=torch.float64)
tensor([0.5402, 0.4443], dtype=torch.float64)
tensor([0.6437, 0.3472], dtype=torch.float64)
tensor([0.6375, 0.3596], dtype=torch.float64)
tensor([0.6938, 0.3097], dtype=torch.float64)
tensor([0.6753, 0.3322], dtype=torch.float64)
tensor([0.5421, 0.4630], dtype=torch.float64)
tensor([0.3860, 0.6121], dtype=torch.float64)
tensor([0.3813, 0.6115], dtype=torch.float64)
tensor([0.3014, 0.6826], dtype=torch.float64)
tensor([0.3344, 0.6443], dtype=torch.float64)
tensor([0.3402, 0.6327], dtype=torch.float64)
tensor([0.3978, 0.5693], dtype=tor

tensor([0.0080, 0.9460], dtype=torch.float64)
tensor([0.0271, 0.9263], dtype=torch.float64)
tensor([0.1607, 0.7965], dtype=torch.float64)
tensor([0.2467, 0.7162], dtype=torch.float64)
tensor([0.3787, 0.5914], dtype=torch.float64)
tensor([0.5254, 0.4540], dtype=torch.float64)
tensor([0.6329, 0.3553], dtype=torch.float64)
tensor([0.6028, 0.3881], dtype=torch.float64)
tensor([0.6710, 0.3258], dtype=torch.float64)
tensor([0.6197, 0.3791], dtype=torch.float64)
tensor([0.6329, 0.3674], dtype=torch.float64)
tensor([0.4968, 0.4999], dtype=torch.float64)
tensor([0.4211, 0.5697], dtype=torch.float64)
tensor([0.4469, 0.5422], dtype=torch.float64)
tensor([0.6274, 0.3674], dtype=torch.float64)
tensor([0.7012, 0.3007], dtype=torch.float64)
tensor([0.8154, 0.1955], dtype=torch.float64)
tensor([0.7728, 0.2413], dtype=torch.float64)
tensor([0.7794, 0.2363], dtype=torch.float64)
tensor([0.7342, 0.2807], dtype=torch.float64)
tensor([0.6888, 0.3238], dtype=torch.float64)
tensor([0.6770, 0.3330], dtype=tor

In [288]:
from __future__ import print_function
import argparse
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import math
import pandas as pd

# #------------------------------------------------------------------------------------------------

class Sequence(nn.Module):
    global window
    def __init__(self):
        super(Sequence, self).__init__()
        self.lstm1 = nn.LSTMCell(len(features), window)
        self.lstm2 = nn.LSTMCell(window, window)
        self.linear = nn.Linear(window, 2)

    def forward(self, input, future = 0):
        outputs = []
        h_t = torch.zeros(input.size(0), window, dtype=torch.double)
        c_t = torch.zeros(input.size(0), window, dtype=torch.double)
        h_t2 = torch.zeros(input.size(0), window, dtype=torch.double)
        c_t2 = torch.zeros(input.size(0), window, dtype=torch.double)

        for t in range(input.size(1)):
            input_t = input[:, t, :]
            h_t, c_t = self.lstm1(input_t, (h_t, c_t))
            h_t2, c_t2 = self.lstm2(h_t, (h_t2, c_t2))
            output = self.linear(h_t2)
            outputs.append(output.unsqueeze(1))
        for i in range(future):# if we should predict the future
            h_t, c_t = self.lstm1(output, (h_t, c_t))
            h_t2, c_t2 = self.lstm2(h_t, (h_t2, c_t2))
            output = self.linear(h_t2)
            outputs.append(output.unsqueeze(1))
        outputs = torch.cat(outputs, dim=1)
        return outputs
    
class CustomLoss(nn.Module):
    def __init__(self, penalty_weight=1.0, sign_penalty_weight=1.0):
        super(CustomLoss, self).__init__()
        self.mse_loss = nn.MSELoss()
        self.penalty_weight = penalty_weight
        self.sign_penalty_weight = sign_penalty_weight

    def forward(self, predictions, targets):
        # Mean Squared Error Loss
        mse = self.mse_loss(predictions, targets)
        
        # Penalty for predictions close to zero
        zero_penalty = self.penalty_weight * torch.mean(torch.exp(-torch.abs(predictions)))
        
        # Penalty for incorrect signs
        sign_penalty = self.sign_penalty_weight * torch.mean((predictions * targets < 0).float())
        
        # Total loss
        total_loss = mse + zero_penalty + sign_penalty
        return total_loss

In [312]:
def train(learning_rate, data, prices, steps):
    print("Begin Training")
    num_train = int(data.shape[0]*0.8)
    
    data = torch.stack([data[i:i+window] for i in range(data.shape[0] - window+1)])
    input = data[:num_train,:-1]
    target = data[:num_train,-1:,0:1]
    
    output_target_flat = target.view(-1)
    target_fuzzy = torch.zeros((output_target_flat.size(0), 2), dtype=torch.double)
    target_fuzzy[output_target_flat > 0, 0] = 1.0
    target_fuzzy[output_target_flat <= 0, 1] = 1.0
    target = target_fuzzy.view(target.size(0), 1, 2)
    
    test_input = data[num_train+window:,:-1]
    test_target = data[num_train+window:,-1:,0:1]
    output_target_flat = test_target.view(-1)
    target_fuzzy = torch.zeros((output_target_flat.size(0), 2), dtype=torch.double)
    target_fuzzy[output_target_flat > 0, 0] = 1
    target_fuzzy[output_target_flat <= 0, 1] = 1
    test_target = target_fuzzy.view(test_target.size(0), 1, 2)
    seq = Sequence()
    seq.double()
    criterion = nn.MSELoss()
    optimizer = optim.LBFGS(seq.parameters(), lr=learning_rate)

    train_loss = 0
    test_loss = 0
    p = []
    nav = []
    for i in range(steps):
        print('STEP: ', i)
        def closure():
            optimizer.zero_grad()
            out = seq(input)
            last = out[:, -1:, :]
            loss = criterion(last, target)
#             print('loss:', loss.item())
            loss.backward()
            return loss
        optimizer.step(closure)

        with torch.no_grad():
            actual = []
            predicted = []
            test_prices = prices[num_train+window:]
            test = test_input[0:1]
            real = []
            
            correct_up = 0
            went_up = 0
            correct_down = 0
            went_down = 0
            omitted = 0
            last_price = test_prices[0]
            
            for x in range(test.size(1)-1):
                value = test[0,x,0].item()
                actual.append(value)
            for x2 in range(test_input.size(0)):
                # graph returns
                actual.append(test_input[x2,-1,0].item())
                pred = seq(test_input[x2:x2+1,:,:])
                o = pred[-1, -1, :]
                last = 0
                if o[0] > 0.5:
                    last = 1
                if o[1] > 0.4:
                    last = -1
                predicted.append(last)
                real.append(((test_prices[x2]-last_price)/test_prices[x2])*10)                    
                
                # Compute loss
                if (test_prices[x2] > last_price):
                    if last > 0:
                        correct_up += 1
                    else:
                        test_loss += o[1]
                    went_up +=1
                if (test_prices[x2] < last_price):
                    if last < 0:
                        correct_down += 1
                    else:
                        test_loss += o[0]
                    went_down +=1
                if last == 0:
                    omitted +=1
                last_price = test_prices[x2]
            
                
            print(f'up correct: {correct_up}/{went_up}')
            print(f'down correct: {correct_down}/{went_down}')
            print(f'total correct: {correct_down+correct_up}/{went_up+went_down-omitted}')
            print(f'omitted: {omitted}/{went_up+went_down}')

            # draw the result
            array1 = actual
            array2 = predicted
            x1 = np.arange(len(array1))  
            x2 = np.arange(len(array2)) + test.size(1)
            plt.figure(figsize=(10, 5))
            plt.plot(x1, array1, label='Actual', color='blue')
            plt.plot(x2, array2, label='Prediction', color='grey', linestyle='--')
            plt.plot(x2, real, label='Prediction', color='red')
            plt.savefig('predict%d.pdf'%i)
            plt.close()

    return train_loss, test_loss, seq


In [290]:
def test(funds, data, prices, seq): 
    data = torch.stack([data[i:i+window] for i in range(data.shape[0] - window+1)])
    test_input = data[:,:-1]
    
    with torch.no_grad():
        test_prices = prices[window:]
        test = test_input[0:1]

        assets = 0
        nav = []
        p = []
        counter = 0
        bought_price = 0
        for x2 in range(test_input.size(0)):          
            pred = seq(test_input[x2:x2+1,:,:])
            o = pred[-1, -1, :]
            last = 0
            if o[0] > 0.5:
                last = 1
            if o[1] > 0.5:
                last = -1

            # Compute nav
            if funds != 0 and last != 0:
                if last > 0:
                    assets = funds/test_prices[x2] 
                if last < 0:
                    assets = -funds/test_prices[x2]
                bought_price = test_prices[x2]
                funds = 0
            if assets != 0:
                counter+=1
                if assets > 0 and (test_prices[x2] > bought_price or counter == 3):
                    counter = 0
                    funds = assets * test_prices[x2]
                    assets = 0
                if assets < 0 and (test_prices[x2] < bought_price or counter == 3):
                    counter = 0
                    funds = assets*test_prices[x2] - (assets * bought_price)*2
                    assets = 0
            nav_item = funds if funds != 0 else abs(assets)*test_prices[x2]
#             print(funds, assets, last, test_prices[x2])
            nav.append(nav_item)
            p.append(test_prices[x2])

        return nav, p


In [291]:
def test2(funds, data, prices, seq):
    data = torch.stack([data[i:i+window] for i in range(data.shape[0] - window+1)])
    test_input = data[window:,:-1]
    
    with torch.no_grad():
        test_prices = prices[window:]
        assets = 0
        nav = []
        p = []
        counter = 0
        bought_price = 0
        for x2 in range(test_input.size(0)):
            pred = seq(test_input[x2:x2+1,:,:])
            o = pred[-1, -1, :]
            last = 0
            if o[0] > 0.5:
                last = 1
            if o[1] > 0.5:
                last = -1

            # Compute nav
            if funds != 0 and last != 0:
                if last > 0:
                    assets = funds/test_prices[x2] 
                if last < 0:
                    assets = -funds/test_prices[x2]
                bought_price = test_prices[x2]
                funds = 0
            if assets != 0:
                counter+=1
                if assets > 0 and (test_prices[x2] > bought_price or counter == 3):
                    counter = 0
                    funds = assets * test_prices[x2]
                    assets = 0
                if assets < 0 and (test_prices[x2] < bought_price or counter == 3):
                    counter = 0
                    funds = assets*test_prices[x2] - (assets * bought_price)*2
                    assets = 0
            nav_item = funds if funds != 0 else abs(assets)*test_prices[x2]
            nav.append(nav_item)
            p.append(test_prices[x2])                    

    return nav, p
